import { Contact } from '../contacts/Contact';
import { normalizePath, TFile } from 'obsidian';
import { Context } from '../obsidian/Context';
import { ContactFileProcessor } from './ContactFileProcessor';
import { formatBirthday } from './formatBirthday';
import { getGroupLetter, slugify } from '../contacts/slugify';

const toYamlInlineArray = (values: string[] | undefined): string => {
  if (!values || values.length === 0) {
    return '[]';
  }
  return '[' + values.map(v => `'${v.replace(/'/g, "''")}'`).join(', ') + ']';
};

export class SyncContactAction {
  readonly contact: Contact;
  readonly context: Context;

  constructor(context: Context, contact: Contact) {
    this.context = context;
    this.contact = contact;
  }

  getContactFolder(): string {
    const root = this.context.settings.contactsFolder;
    if (!this.context.settings.groupByFirstLetter) {
      return root;
    }
    return root + '/' + getGroupLetter(this.contact.name);
  }

  getFilepath(): string {
    const filename = slugify(this.contact.name);
    return normalizePath(this.getContactFolder() + '/' + filename + '.md');
  }

  replaceTemplateVariables(body: string): string {
    return body
      .replace(/{{contactName}}/g, this.contact.name)
      .replace(/{{contactUID}}/g, this.contact.uid ?? '')
      .replace(/{{contactEmail}}/g, this.contact.emails?.[0] ?? '')
      .replace(/{{contactPhone}}/g, this.contact.phones?.[0] ?? '')
      .replace(/{{contactWebsite}}/g, this.contact.website?.[0] ?? '')
      .replace(/{{contactAddress}}/g, this.contact.address?.[0] ?? '')
      .replace(/{{contactEmails}}/g, toYamlInlineArray(this.contact.emails))
      .replace(/{{contactPhones}}/g, toYamlInlineArray(this.contact.phones))
      .replace(/{{contactWebsites}}/g, toYamlInlineArray(this.contact.website))
      .replace(/{{contactAddresses}}/g, toYamlInlineArray(this.contact.address))
      .replace(/{{contactBirthday}}/g, this.contact.birthday ? formatBirthday(this.contact.birthday) : '')
      .replace(/{{snake_contactName}}/g, this.contact.name.toLowerCase().replace(/ /g, '_'));
  }

  async execute() {
    await this.createContactsFolder();
    const filename = await this.context.fileHelper.getAbstractFileByPath(this.getFilepath());
    if (!(filename instanceof TFile)) {
      await this.createContact();
      return;
    }

    // Update contact
    if (!this.context.settings.updateContacts) {
      return;
    }

    await this.updateContactIn(filename);
  }

  private async createContactsFolder(): Promise<void> {
    await this.context.fileHelper.createFolderIfNotExists(this.context.settings.contactsFolder);
    if (this.context.settings.groupByFirstLetter) {
      await this.context.fileHelper.createFolderIfNotExists(this.getContactFolder());
    }
  }

  private toMarkdown(): string {
    const rawMarkdown = this.context.settings.contactTemplate;
    const markdown = this.replaceTemplateVariables(rawMarkdown);
    return this.getAutogeneratedMarkdownTag() + '\n' + markdown + '\n' + this.getAutogeneratedMarkdownTag();
  }

  private toProperties(): string {
    return this.replaceTemplateVariables(this.context.settings.propertiesTemplate);
  }

  private async createContact(): Promise<void> {
    const newContactMarkdown = `${this.toProperties()}\n${this.toMarkdown()}`;
    await this.context.fileHelper.create(this.getFilepath(), newContactMarkdown);
  }

  private getAutogeneratedMarkdownTag(): string {
    return '<!-- ' + this.context.settings.autogeneratedTag + ' -->';
  }

  private async updateContactIn(file: TFile) {
    const processor = new ContactFileProcessor(
      this.getAutogeneratedMarkdownTag(),
      this.toProperties(),
      this.toMarkdown()
    );
    await this.context.fileHelper.process(file, oldContent => processor.execute(oldContent));
  }
}
