import { Contact } from '../contacts/Contact';
import { normalizePath, TFile } from 'obsidian';
import { Context } from '../obsidian/Context';
import { ContactFileProcessor } from './ContactFileProcessor';

export class SyncContactAction {
	readonly contact: Contact;
	readonly context: Context;

	constructor(context: Context, contact: Contact) {
		this.context = context;
		this.contact = contact;
	}

	getFilepath(): string {
		return normalizePath(this.context.settings.contactsFolder + '/' + this.contact.name + '.md');
	}

	async execute() {
		await this.createContactsFolder();
		const filename = await this.context.fileHelper.getAbstractFileByPath(this.getFilepath());
		if (!(filename instanceof TFile)) {
			await this.createContact();
			return;
		}

		// Update contact
		if (!this.context.settings.updateContacts) {
			return;
		}

		await this.updateContactIn(filename);
	}

	private async createContactsFolder(): Promise<void> {
		return this.context.fileHelper.createFolderIfNotExists(this.context.settings.contactsFolder);
	}

	private toMarkdown(): string {
		const markdown = `
# ${this.contact.name}
		`;
		return this.getAutogeneratedMarkdownTag() + '\n' + markdown + '\n' + this.getAutogeneratedMarkdownTag();
	}

	private toProperties(): string {
		return `---
type: 'people'
---
`
	}

	private async createContact(): Promise<void> {
		const newContactMarkdown = `${this.toProperties()}\n${this.toMarkdown()}`;
		await this.context.fileHelper.create(this.getFilepath(), newContactMarkdown);
	}

	private getAutogeneratedMarkdownTag(): string {
		return '<!-- ' + this.context.settings.autogeneratedTag + ' -->';
	}

	private async updateContactIn(file: TFile) {
		const processor = new ContactFileProcessor(
			this.getAutogeneratedMarkdownTag(),
			this.toProperties(),
			this.toMarkdown()
		);
		await this.context.fileHelper.process(file, (oldContent) =>
			processor.execute(oldContent));
	}
}
