import { App, PluginSettingTab, Setting } from 'obsidian';
import MacSyncContactsPlugin from '../../main';
import { FolderSuggest } from './suggest/FolderSuggest';

export const DEFAULT_SETTINGS: MacSyncContactsPluginSettings = {
	contactsFolder: 'People',
	updateContacts: false,
	autogeneratedTag: 'MAC_SYNC_CONTACTS_AUTOGENERATED'
}

export interface MacSyncContactsPluginSettings {
	contactsFolder: string;
	updateContacts: boolean;
	autogeneratedTag: string;
}

export class SettingsTab extends PluginSettingTab {
	plugin: MacSyncContactsPlugin;

	constructor(app: App, plugin: MacSyncContactsPlugin) {
		super(app, plugin);
		this.plugin = plugin;
	}

	display(): void {
		this.containerEl.empty();

		this.addContactsFolder();
		this.addUpdateContacts();
	}

	private addContactsFolder() {
		new Setting(this.containerEl)
			.setName('Contacts folder')
			.setDesc('Select the folder where your contacts are stored')
			.addSearch(search => {
				new FolderSuggest(search.inputEl);
				search.setPlaceholder('Contacts folder')
					.setValue(this.plugin.settings.contactsFolder)
					.onChange(async (value) => {
						this.plugin.settings.contactsFolder = value;
						await this.plugin.saveSettings();
					})
			});
	}


	private addUpdateContacts() {
		new Setting(this.containerEl)
			.setName('Update contacts?')
			.setDesc('Update contacts when they are changed in Contacts.app. Can lose the obsidian data')
			.addToggle(toggle => {
				toggle.setValue(this.plugin.settings.updateContacts)
					.onChange(async (value) => {
						this.plugin.settings.updateContacts = value;
						await this.plugin.saveSettings();
					})
			});
	}
}
