import { App, Notice, PluginSettingTab, Setting } from 'obsidian';
import MacSyncContactsPlugin from '../../main';
import { FolderSuggest } from './suggest/FolderSuggest';
import { CONTACT_FIELD_KEYS, CONTACT_FIELD_LABELS, ContactFieldKey, FieldMapping } from '../actions/contactFields';

const DEFAULT_CONTACT_TEMPLATE = `# {{contactName}}

`;

const DEFAULT_PROPERTIES_TEMPLATE = `---
type: 'people'
contactUID: '{{contactUID}}'
name: '{{contactName}}'
emails: {{contactEmails}}
phones: {{contactPhones}}
websites: {{contactWebsites}}
addresses: {{contactAddresses}}
birthday: '{{contactBirthday}}'
---
`;

export const DEFAULT_SETTINGS: MacSyncContactsPluginSettings = {
  contactsFolder: 'People',
  updateContacts: false,
  groupByFirstLetter: false,
  generateSummary: true,
  autogeneratedTag: 'MAC_SYNC_CONTACTS_AUTOGENERATED',
  contactTemplate: DEFAULT_CONTACT_TEMPLATE,
  propertiesTemplate: DEFAULT_PROPERTIES_TEMPLATE,
  fieldMappings: []
};

export interface MacSyncContactsPluginSettings {
  contactTemplate: string;
  contactsFolder: string;
  updateContacts: boolean;
  groupByFirstLetter: boolean;
  generateSummary: boolean;
  autogeneratedTag: string;
  propertiesTemplate: string;
  fieldMappings: FieldMapping[];
}

export class SettingsTab extends PluginSettingTab {
  plugin: MacSyncContactsPlugin;

  constructor(app: App, plugin: MacSyncContactsPlugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display(): void {
    this.containerEl.empty();

    this.addContactsFolder();
    this.addUpdateContacts();
    this.addGroupByFirstLetter();
    this.addGenerateSummary();
    this.addContactTemplate();
    this.addPropertiesTemplate();
    this.addFieldMappings();
  }

  private addFieldMappings() {
    new Setting(this.containerEl)
      .setName('Field mappings')
      .setDesc(
        'Map a Contacts field to your own variable name. Use it as {{alias}} in the templates above. ' +
          'For multivalued fields (emails, phones…) the first value is used.'
      )
      .setHeading();

    const mappings = this.plugin.settings.fieldMappings;

    mappings.forEach((mapping, index) => {
      new Setting(this.containerEl)
        .addDropdown(dropdown => {
          CONTACT_FIELD_KEYS.forEach(key => dropdown.addOption(key, CONTACT_FIELD_LABELS[key]));
          dropdown.setValue(mapping.source).onChange(async value => {
            mapping.source = value as ContactFieldKey;
            await this.plugin.saveSettings();
          });
        })
        .addText(text => {
          text
            .setPlaceholder('alias (e.g. username)')
            .setValue(mapping.alias)
            .onChange(async value => {
              mapping.alias = value;
              await this.plugin.saveSettings();
            });
        })
        .addExtraButton(button => {
          button
            .setIcon('trash')
            .setTooltip('Remove mapping')
            .onClick(async () => {
              mappings.splice(index, 1);
              await this.plugin.saveSettings();
              this.display();
            });
        });
    });

    new Setting(this.containerEl).addButton(button => {
      button
        .setButtonText('Add mapping')
        .setCta()
        .onClick(async () => {
          mappings.push({ source: 'name', alias: '' });
          await this.plugin.saveSettings();
          this.display();
        });
    });
  }

  private addGenerateSummary() {
    new Setting(this.containerEl)
      .setName('Generate sync summary')
      .setDesc('Write a _sync-summary.md inside the contacts folder after each sync')
      .addToggle(toggle => {
        toggle.setValue(this.plugin.settings.generateSummary).onChange(async value => {
          this.plugin.settings.generateSummary = value;
          await this.plugin.saveSettings();
        });
      });
  }

  private addGroupByFirstLetter() {
    new Setting(this.containerEl)
      .setName('Group by first letter')
      .setDesc('Place each contact inside a subfolder named after the first letter of their name')
      .addToggle(toggle => {
        toggle.setValue(this.plugin.settings.groupByFirstLetter).onChange(async value => {
          this.plugin.settings.groupByFirstLetter = value;
          await this.plugin.saveSettings();
        });
      });
  }

  private addContactsFolder() {
    new Setting(this.containerEl)
      .setName('Contacts folder')
      .setDesc('Select the folder where your contacts are stored')
      .addSearch(search => {
        new FolderSuggest(search.inputEl);
        search
          .setPlaceholder('Contacts folder')
          .setValue(this.plugin.settings.contactsFolder)
          .onChange(async value => {
            this.plugin.settings.contactsFolder = value;
            await this.plugin.saveSettings();
          });
      });
  }

  private addUpdateContacts() {
    new Setting(this.containerEl)
      .setName('Update contacts?')
      .setDesc('Update contacts when they are changed in Contacts.app. Can lose the obsidian data')
      .addToggle(toggle => {
        toggle.setValue(this.plugin.settings.updateContacts).onChange(async value => {
          this.plugin.settings.updateContacts = value;
          await this.plugin.saveSettings();
        });
      });
  }

  private addContactTemplate() {
    new Setting(this.containerEl)
      .setName('Contact template')
      .setDesc(
        createFragment(fragment => {
          fragment.append(
            'Template for contact file\n. Using variables like {{contactName}} and {{contactEmail}}.\n',
            fragment.createEl('a', {
              text: 'Reference',
              href: 'https://github.com/raulanatol/obsidian-mac-sync-contacts?tab=readme-ov-file#template-variables'
            })
          );
        })
      )
      .addTextArea(text => {
        text
          .setPlaceholder('Contact template')
          .setValue(this.plugin.settings.contactTemplate)
          .onChange(async value => {
            this.plugin.settings.contactTemplate = value;
            await this.plugin.saveSettings();
          });
        text.inputEl.setAttr('rows', 25);
        text.inputEl.setAttr('cols', 50);
      })
      .addExtraButton(button => {
        button
          .setIcon('reset')
          .setTooltip('Reset to default')
          .onClick(async () => {
            this.plugin.settings.contactTemplate = DEFAULT_SETTINGS.contactTemplate;
            await this.plugin.saveSettings();
            this.display();
            new Notice('Template reset to default');
          });
      });
  }

  private addPropertiesTemplate() {
    new Setting(this.containerEl)
      .setName('Properties template')
      .setDesc(
        createFragment(fragment => {
          fragment.append(
            'Properties in contact file\n. Using variables like {{contactName}} and {{contactEmail}}.\n',
            fragment.createEl('a', {
              text: 'Reference',
              href: 'https://github.com/raulanatol/obsidian-mac-sync-contacts?tab=readme-ov-file#template-variables'
            })
          );
        })
      )
      .addTextArea(text => {
        text
          .setPlaceholder('Properties template')
          .setValue(this.plugin.settings.propertiesTemplate)
          .onChange(async value => {
            this.plugin.settings.propertiesTemplate = value;
            await this.plugin.saveSettings();
          });
        text.inputEl.setAttr('rows', 25);
        text.inputEl.setAttr('cols', 50);
      })
      .addExtraButton(button => {
        button
          .setIcon('reset')
          .setTooltip('Reset to default')
          .onClick(async () => {
            this.plugin.settings.propertiesTemplate = DEFAULT_SETTINGS.propertiesTemplate;
            await this.plugin.saveSettings();
            this.display();
            new Notice('Properties reset to default');
          });
      });
  }
}
